name: cron

on:
  workflow_dispatch:
  schedule:
    - cron: '* * * * 1-5'
    
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Request PR Review
        uses: ygnoh/actions-request-pr-review@v0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          slackBotToken: ${{ secrets.SLACK_BOT_TOKEN }}
          repoUrl: 'github.com/ygnoh/actions-tutorial'
