name: cron

on:
  schedule:
    - cron: '* * * * *'
    
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting action step
        id: greeting
        uses: ygnoh/actions-greeting@v1.0
        with:
          who-to-greet: 'ygnoh'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.greeting.outputs.time }}"
