name: cron

on:
  workflow_dispatch:
  schedule:
    - cron: '12 5 * * 1-5'
    
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello, world!~~!
#         uses: ygnoh/actions-request-pr-review@v0.1
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           slackBotToken: ${{ secrets.SLACK_BOT_TOKEN }}
