name: mergeable
on:
  pull_request:
    types: [opened, reopened, review_requested, review_request_removed, ready_for_review]
  pull_request_review:
  
jobs:
  mergeable:
    runs-on: ubuntu-latest
    steps:
      - name: Mergeable
        uses: ygnoh/actions-mergeable@v0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
