name: mergeable
on:
  pull_request:
    types:
      - labeled
      - unlabeled
#      - synchronize
#      - opened
#      - edited
#      - ready_for_review
#      - reopened
#      - unlocked
#  pull_request_review:
#    types:
#      - submitted
#  check_suite:
#    types:
#      - completed
  
jobs:
  mergeable:
    runs-on: ubuntu-latest
    steps:
      - name: Mergeable
      - uses: actions/setup-node@v3
        with:
          node-version: '12'
      - run: node mergeable.js
