name: Request PR Review

on:
  workflow_dispatch:
    
jobs:
  requestPrReview:
    runs-on: ubuntu-latest
    steps:
      - name: Request PR Review
        uses: ygnoh/actions-request-pr-review@v0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          slackBotToken: ${{ secrets.SLACK_BOT_TOKEN }}
